[workspace]
members = [
    "open-variant",
    "arrow-open-variant",
]
resolver = "2"

[workspace.dependencies]
arrow-array = "52"
arrow-buffer = "52"
arrow-cast = "52"
arrow-schema = "52"

[workspace.lints.clippy]
dbg_macro = "deny"
print_stdout = "deny"
